# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-25 02:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('customer_id', models.CharField(db_column='CUSTOMER_ID', max_length=25, primary_key=True, serialize=False, verbose_name='Customer|customer id')),
                ('customer_name', models.CharField(db_column='CUSTOMER_NAME', max_length=100, verbose_name='customer name')),
                ('business_div', models.CharField(blank=True, choices=[('1', 'SELL'), ('2', 'BUY')], db_column='BUSINESS_DIV', default='1', max_length=1, verbose_name='business division')),
                ('business_type', models.CharField(blank=True, db_column='BUSINESS_TYPE', max_length=50, verbose_name='business type')),
                ('business_no', models.CharField(blank=True, db_column='BUSINESS_NO', max_length=50, verbose_name='business no')),
                ('owner', models.CharField(blank=True, db_column='OWNER', max_length=10, verbose_name='owner')),
                ('business_item', models.CharField(blank=True, db_column='BUSINESS_ITEM', max_length=100, verbose_name='business item')),
                ('business_status', models.CharField(blank=True, db_column='BUSINESS_STATUS', max_length=100, verbose_name='business status')),
                ('customer_status', models.CharField(blank=True, db_column='CUSTOMER_STATUS', max_length=100, verbose_name='customer status')),
                ('country', models.CharField(blank=True, db_column='COUNTRY', max_length=100, verbose_name='country')),
                ('address_1', models.CharField(blank=True, db_column='ADDRESS_1', max_length=100, verbose_name='address 1')),
                ('address_2', models.CharField(blank=True, db_column='ADDRESS_2', max_length=100, verbose_name='address 2')),
                ('post_no', models.CharField(blank=True, db_column='POST_NO', max_length=100, verbose_name='post no')),
                ('phone_no', models.CharField(blank=True, db_column='PHONE_NO', max_length=100, verbose_name='phone no')),
                ('fax_no', models.CharField(blank=True, db_column='FAX_NO', max_length=100, verbose_name='fax no')),
                ('mobile_no', models.CharField(blank=True, db_column='MOBILE_NO', max_length=100, verbose_name='mobile no')),
                ('email', models.CharField(blank=True, db_column='EMAIL', max_length=100, verbose_name='email')),
                ('user_name_1', models.CharField(blank=True, db_column='USER_NAME_1', max_length=100, verbose_name='user name 1')),
                ('mobile_no_1', models.CharField(blank=True, db_column='MOBILE_NO_1', max_length=100, verbose_name='mobile no 1')),
                ('email_1', models.CharField(blank=True, db_column='EMAIL_1', max_length=100, verbose_name='email 1')),
                ('user_name_2', models.CharField(blank=True, db_column='USER_NAME_2', max_length=100, verbose_name='user name 2')),
                ('mobile_no_2', models.CharField(blank=True, db_column='MOBILE_NO_2', max_length=100, verbose_name='mobile no 2')),
                ('email_2', models.CharField(blank=True, db_column='EMAIL_2', max_length=100, verbose_name='email 2')),
                ('bank_name', models.CharField(blank=True, db_column='BANK_NAME', max_length=100, verbose_name='bank name')),
                ('account_no', models.CharField(blank=True, db_column='ACCOUNT_NO', max_length=100, verbose_name='account no')),
                ('account_name', models.CharField(blank=True, db_column='ACCOUNT_NAME', max_length=100, verbose_name='account name')),
                ('cus_cmf_1', models.CharField(blank=True, db_column='CUS_CMF_1', max_length=100)),
                ('cus_cmf_2', models.CharField(blank=True, db_column='CUS_CMF_2', max_length=100)),
                ('cus_cmf_3', models.CharField(blank=True, db_column='CUS_CMF_3', max_length=100)),
                ('cus_cmf_4', models.CharField(blank=True, db_column='CUS_CMF_4', max_length=100)),
                ('cus_cmf_5', models.CharField(blank=True, db_column='CUS_CMF_5', max_length=100)),
                ('cus_cmf_6', models.CharField(blank=True, db_column='CUS_CMF_6', max_length=100)),
                ('cus_cmf_7', models.CharField(blank=True, db_column='CUS_CMF_7', max_length=100)),
                ('cus_cmf_8', models.CharField(blank=True, db_column='CUS_CMF_8', max_length=100)),
                ('cus_cmf_9', models.CharField(blank=True, db_column='CUS_CMF_9', max_length=100)),
                ('cus_cmf_10', models.CharField(blank=True, db_column='CUS_CMF_10', max_length=100)),
                ('create_time', models.DateTimeField(auto_now_add=True, db_column='CREATE_TIME', verbose_name='create time')),
                ('update_time', models.DateTimeField(auto_now=True, db_column='UPDATE_TIME', verbose_name='update time')),
                ('create_user', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='create_user', to=settings.AUTH_USER_MODEL, verbose_name='create user')),
                ('update_user', models.ForeignKey(default=' ', on_delete=django.db.models.deletion.CASCADE, related_name='update_user', to=settings.AUTH_USER_MODEL, verbose_name='update user')),
            ],
            options={
                'verbose_name': 'Customer',
                'verbose_name_plural': 'Customers',
                'db_table': 'jbascusmst',
                'managed': True,
            },
        ),
    ]
