CREATE TABLE `jbascusmst` (
	`CUSTOMER_ID` VARCHAR(25) NOT NULL COMMENT '거래처번호' COLLATE 'utf8mb4_bin',
	`CUSTOMER_NAME` VARCHAR(100) NOT NULL COMMENT '거래처명' COLLATE 'utf8mb4_bin',
	`BUSINESS_DIV` CHAR(1) NOT NULL COMMENT '사업자구분' COLLATE 'utf8mb4_bin',
	`BUSINESS_TYPE` VARCHAR(50) NOT NULL COMMENT '사업자종류' COLLATE 'utf8mb4_bin',
	`BUSINESS_NO` VARCHAR(50) NOT NULL COMMENT '사업자번호(주민번호)' COLLATE 'utf8mb4_bin',
	`OWNER` VARCHAR(10) NOT NULL COMMENT '대표자명' COLLATE 'utf8mb4_bin',
	`BUSINESS_ITEM` VARCHAR(100) NOT NULL COMMENT '종목' COLLATE 'utf8mb4_bin',
	`BUSINESS_STATUS` VARCHAR(100) NOT NULL COMMENT '업태' COLLATE 'utf8mb4_bin',
	`CUSTOMER_STATUS` VARCHAR(100) NOT NULL COMMENT '거래처상태' COLLATE 'utf8mb4_bin',
	`COUNTRY` VARCHAR(100) NOT NULL COMMENT '국가' COLLATE 'utf8mb4_bin',
	`ADDRESS_1` VARCHAR(100) NOT NULL COMMENT '주소' COLLATE 'utf8mb4_bin',
	`ADDRESS_2` VARCHAR(100) NOT NULL COMMENT '상세주소' COLLATE 'utf8mb4_bin',
	`POST_NO` VARCHAR(100) NOT NULL COMMENT '우편번호' COLLATE 'utf8mb4_bin',
	`PHONE_NO` VARCHAR(100) NOT NULL COMMENT '회사 전화번호' COLLATE 'utf8mb4_bin',
	`FAX_NO` VARCHAR(100) NOT NULL COMMENT '회사 팩스번호' COLLATE 'utf8mb4_bin',
	`MOBILE_NO` VARCHAR(100) NOT NULL COMMENT '회사 모바일번호' COLLATE 'utf8mb4_bin',
	`EMAIL` VARCHAR(100) NOT NULL COMMENT '회사 이메일주소' COLLATE 'utf8mb4_bin',
	`USER_NAME_1` VARCHAR(100) NOT NULL COMMENT '담당자1' COLLATE 'utf8mb4_bin',
	`MOBILE_NO_1` VARCHAR(100) NOT NULL COMMENT '담당자1 모바일 번호' COLLATE 'utf8mb4_bin',
	`EMAIL_1` VARCHAR(100) NOT NULL COMMENT '담당자1 이메일 주소' COLLATE 'utf8mb4_bin',
	`USER_NAME_2` VARCHAR(100) NOT NULL COMMENT '담당자2' COLLATE 'utf8mb4_bin',
	`MOBILE_NO_2` VARCHAR(100) NOT NULL COMMENT '담당자2 모바일 번호' COLLATE 'utf8mb4_bin',
	`EMAIL_2` VARCHAR(100) NOT NULL COMMENT '담당자2 이메일 주소' COLLATE 'utf8mb4_bin',
	`BANK_NAME` VARCHAR(100) NOT NULL COMMENT '거래은행' COLLATE 'utf8mb4_bin',
	`ACCOUNT_NO` VARCHAR(100) NOT NULL COMMENT '계좌번호' COLLATE 'utf8mb4_bin',
	`ACCOUNT_NAME` VARCHAR(100) NOT NULL COMMENT '예금주명' COLLATE 'utf8mb4_bin',
	`CUS_CMF_1` VARCHAR(100) NOT NULL COMMENT '사용자정의필드1' COLLATE 'utf8mb4_bin',
	`CUS_CMF_2` VARCHAR(100) NOT NULL COMMENT '사용자정의필드2' COLLATE 'utf8mb4_bin',
	`CUS_CMF_3` VARCHAR(100) NOT NULL COMMENT '사용자정의필드3' COLLATE 'utf8mb4_bin',
	`CUS_CMF_4` VARCHAR(100) NOT NULL COMMENT '사용자정의필드4' COLLATE 'utf8mb4_bin',
	`CUS_CMF_5` VARCHAR(100) NOT NULL COMMENT '사용자정의필드5' COLLATE 'utf8mb4_bin',
	`CUS_CMF_6` VARCHAR(100) NOT NULL COMMENT '사용자정의필드6' COLLATE 'utf8mb4_bin',
	`CUS_CMF_7` VARCHAR(100) NOT NULL COMMENT '사용자정의필드7' COLLATE 'utf8mb4_bin',
	`CUS_CMF_8` VARCHAR(100) NOT NULL COMMENT '사용자정의필드8' COLLATE 'utf8mb4_bin',
	`CUS_CMF_9` VARCHAR(100) NOT NULL COMMENT '사용자정의필드9' COLLATE 'utf8mb4_bin',
	`CUS_CMF_10` VARCHAR(100) NOT NULL COMMENT '사용자정의필드10' COLLATE 'utf8mb4_bin',
	`CREATE_USER` VARCHAR(100) NOT NULL COMMENT '등록자' COLLATE 'utf8mb4_bin',
	`CREATE_TIME` VARCHAR(14) NOT NULL COMMENT '등록일시' COLLATE 'utf8mb4_bin',
	`UPADTE_USER` VARCHAR(100) NOT NULL COMMENT '수정자' COLLATE 'utf8mb4_bin',
	`UPDATE_TIME` VARCHAR(14) NOT NULL COMMENT '수정일시' COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`CUSTOMER_ID`)
)
COMMENT='거래처 기준정보'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;


CREATE TABLE `jbasitmdtl` (
	`ITEM_CODE` VARCHAR(100) NOT NULL COMMENT '품목코드' COLLATE 'utf8mb4_bin',
	`ITEM_VERSION` INT(11) NOT NULL COMMENT '품목버전',
	`ITEM_NO` VARCHAR(100) NOT NULL COMMENT '품목번호' COLLATE 'utf8mb4_bin',
	`ITEM_COLOR` VARCHAR(200) NOT NULL COMMENT '품목색상' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_1` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 1' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_2` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 2' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_3` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 3' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_4` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 4' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_5` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 5' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_6` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 6' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_7` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 7' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_8` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 8' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_9` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 9' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_10` VARCHAR(200) NOT NULL COMMENT '품목상세 사용자 필드 10' COLLATE 'utf8mb4_bin',
	`CREATE_USER` VARCHAR(100) NOT NULL COMMENT '등록자' COLLATE 'utf8mb4_bin',
	`CREATE_TIME` VARCHAR(14) NOT NULL COMMENT '등록일시' COLLATE 'utf8mb4_bin',
	`UPADTE_USER` VARCHAR(100) NOT NULL COMMENT '수정자' COLLATE 'utf8mb4_bin',
	`UPDATE_TIME` VARCHAR(14) NOT NULL COMMENT '수정일시' COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`ITEM_CODE`, `ITEM_VERSION`, `ITEM_NO`)
)
COMMENT='품목상세  기준정보'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;


CREATE TABLE `jbasitmmst` (
	`ITEM_CODE` VARCHAR(100) NOT NULL COMMENT '품목코드' COLLATE 'utf8mb4_bin',
	`ITEM_VERSION` INT(11) NOT NULL COMMENT '품목버전',
	`ITEM_NAME` VARCHAR(200) NOT NULL COMMENT '품목명칭' COLLATE 'utf8mb4_bin',
	`ITEM_GAUGE` VARCHAR(200) NOT NULL COMMENT '품목규격' COLLATE 'utf8mb4_bin',
	`ITEM_COLOR` VARCHAR(200) NOT NULL COMMENT '품목색상' COLLATE 'utf8mb4_bin',
	`BUY_METHOD` VARCHAR(100) NOT NULL COMMENT '구매방법' COLLATE 'utf8mb4_bin',
	`ITEM_CURRENCY` VARCHAR(100) NOT NULL COMMENT '통화' COLLATE 'utf8mb4_bin',
	`BUY_COST` DOUBLE NOT NULL COMMENT '매입가',
	`SELL_COST` DOUBLE NOT NULL COMMENT '판매가',
	`UNIT_COST` DOUBLE NOT NULL COMMENT '단가',
	`ITEM_GROUP_1` VARCHAR(100) NOT NULL COMMENT '품목그룹_1' COLLATE 'utf8mb4_bin',
	`ITEM_GROUP_2` VARCHAR(100) NOT NULL COMMENT '품목그룹_2' COLLATE 'utf8mb4_bin',
	`ITEM_GROUP_3` VARCHAR(100) NOT NULL COMMENT '품목그룹_3' COLLATE 'utf8mb4_bin',
	`ITEM_GROUP_4` VARCHAR(100) NOT NULL COMMENT '품목그룹_4' COLLATE 'utf8mb4_bin',
	`ITEM_GROUP_5` VARCHAR(100) NOT NULL COMMENT '품목그룹_5' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_1` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 1' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_2` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 2' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_3` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 3' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_4` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 4' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_5` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 5' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_6` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 6' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_7` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 7' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_8` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 8' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_9` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 9' COLLATE 'utf8mb4_bin',
	`ITEM_CMF_10` VARCHAR(200) NOT NULL COMMENT '품목 사용자 필드 10' COLLATE 'utf8mb4_bin',
	`CREATE_USER` VARCHAR(100) NOT NULL COMMENT '등록자' COLLATE 'utf8mb4_bin',
	`CREATE_TIME` VARCHAR(14) NOT NULL COMMENT '등록일시' COLLATE 'utf8mb4_bin',
	`UPADTE_USER` VARCHAR(100) NOT NULL COMMENT '수정자' COLLATE 'utf8mb4_bin',
	`UPDATE_TIME` VARCHAR(14) NOT NULL COMMENT '수정일시' COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`ITEM_CODE`, `ITEM_VERSION`)
)
COMMENT='품목 기준정보'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;



CREATE TABLE `jordsaldtl` (
	`SORD_NO` VARCHAR(100) NOT NULL COMMENT '거래번호' COLLATE 'utf8mb4_bin',
	`SORD_SEQ` INT(11) NOT NULL COMMENT '거래상세 순번',
	`SALE_DATE` VARCHAR(14) NOT NULL COMMENT '거래일자' COLLATE 'utf8mb4_bin',
	`ITEM_CODE` VARCHAR(100) NOT NULL COMMENT '품목코드' COLLATE 'utf8mb4_bin',
	`ITEM_VERSION` INT(11) NOT NULL COMMENT '품목 버전',
	`UNIT_COST` DOUBLE NOT NULL COMMENT '단위 가격',
	`UNIT_PROFIT` DOUBLE NOT NULL COMMENT '단위 이익',
	`SO_QTY` DOUBLE NOT NULL COMMENT '거래수량',
	`ITEM_NO` VARCHAR(100) NOT NULL COMMENT '품목번호' COLLATE 'utf8mb4_bin',
	`ITEM_COLOR` VARCHAR(200) NOT NULL COMMENT '품목색상' COLLATE 'utf8mb4_bin',
	`COMMENT` VARCHAR(1000) NOT NULL COMMENT '비고' COLLATE 'utf8mb4_bin',
	`SALE_CMF_1` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 1' COLLATE 'utf8mb4_bin',
	`SALE_CMF_2` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 2' COLLATE 'utf8mb4_bin',
	`SALE_CMF_3` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 3' COLLATE 'utf8mb4_bin',
	`SALE_CMF_4` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 4' COLLATE 'utf8mb4_bin',
	`SALE_CMF_5` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 5' COLLATE 'utf8mb4_bin',
	`SALE_CMF_6` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 6' COLLATE 'utf8mb4_bin',
	`SALE_CMF_7` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 7' COLLATE 'utf8mb4_bin',
	`SALE_CMF_8` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 8' COLLATE 'utf8mb4_bin',
	`SALE_CMF_9` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 9' COLLATE 'utf8mb4_bin',
	`SALE_CMF_10` VARCHAR(200) NOT NULL COMMENT '거래상세 사용자 필드 10' COLLATE 'utf8mb4_bin',
	`CREATE_USER` VARCHAR(100) NOT NULL COMMENT '등록자' COLLATE 'utf8mb4_bin',
	`CREATE_TIME` VARCHAR(14) NOT NULL COMMENT '등록일시' COLLATE 'utf8mb4_bin',
	`UPADTE_USER` VARCHAR(100) NOT NULL COMMENT '수정자' COLLATE 'utf8mb4_bin',
	`UPDATE_TIME` VARCHAR(14) NOT NULL COMMENT '수정일시' COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`SORD_NO`, `SORD_SEQ`)
)
COMMENT='거래상세'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;



CREATE TABLE `jordsalmst` (
	`SORD_NO` VARCHAR(100) NOT NULL COMMENT '거래번호' COLLATE 'utf8mb4_bin',
	`SALE_DATE` VARCHAR(14) NOT NULL COMMENT '거래일자' COLLATE 'utf8mb4_bin',
	`CUSTOMER_ID` VARCHAR(100) NOT NULL COMMENT '고객코드' COLLATE 'utf8mb4_bin',
	`SALE_CMF_1` VARCHAR(200) NOT NULL COMMENT '거래정보  사용자 필드 1' COLLATE 'utf8mb4_bin',
	`SALE_CMF_2` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 2' COLLATE 'utf8mb4_bin',
	`SALE_CMF_3` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 3' COLLATE 'utf8mb4_bin',
	`SALE_CMF_4` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 4' COLLATE 'utf8mb4_bin',
	`SALE_CMF_5` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 5' COLLATE 'utf8mb4_bin',
	`SALE_CMF_6` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 6' COLLATE 'utf8mb4_bin',
	`SALE_CMF_7` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 7' COLLATE 'utf8mb4_bin',
	`SALE_CMF_8` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 8' COLLATE 'utf8mb4_bin',
	`SALE_CMF_9` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 9' COLLATE 'utf8mb4_bin',
	`SALE_CMF_10` VARCHAR(200) NOT NULL COMMENT '거래정보 사용자 필드 10' COLLATE 'utf8mb4_bin',
	`CREATE_USER` VARCHAR(100) NOT NULL COMMENT '등록자' COLLATE 'utf8mb4_bin',
	`CREATE_TIME` VARCHAR(14) NOT NULL COMMENT '등록일시' COLLATE 'utf8mb4_bin',
	`UPADTE_USER` VARCHAR(100) NOT NULL COMMENT '수정자' COLLATE 'utf8mb4_bin',
	`UPDATE_TIME` VARCHAR(14) NOT NULL COMMENT '수정일시' COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`SORD_NO`)
)
COMMENT='거래명세서'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;



CREATE TABLE `jordsalrst` (
	`SRST_NO` VARCHAR(100) NOT NULL COMMENT '결제번호' COLLATE 'utf8mb4_bin',
	`SORD_NO` VARCHAR(100) NOT NULL COMMENT '거래번호' COLLATE 'utf8mb4_bin',
	`SRST_DATE` VARCHAR(14) NOT NULL COMMENT '결제일자' COLLATE 'utf8mb4_bin',
	`SRST_COST` DOUBLE NOT NULL COMMENT '결제금액',
	`SRST_CMF_1` VARCHAR(200) NOT NULL COMMENT '결제정보  사용자 필드 1' COLLATE 'utf8mb4_bin',
	`SRST_CMF_2` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 2' COLLATE 'utf8mb4_bin',
	`SRST_CMF_3` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 3' COLLATE 'utf8mb4_bin',
	`SRST_CMF_4` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 4' COLLATE 'utf8mb4_bin',
	`SRST_CMF_5` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 5' COLLATE 'utf8mb4_bin',
	`SRST_CMF_6` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 6' COLLATE 'utf8mb4_bin',
	`SRST_CMF_7` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 7' COLLATE 'utf8mb4_bin',
	`SRST_CMF_8` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 8' COLLATE 'utf8mb4_bin',
	`SRST_CMF_9` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 9' COLLATE 'utf8mb4_bin',
	`SRST_CMF_10` VARCHAR(200) NOT NULL COMMENT '결제정보 사용자 필드 10' COLLATE 'utf8mb4_bin',
	`CREATE_USER` VARCHAR(100) NOT NULL COMMENT '등록자' COLLATE 'utf8mb4_bin',
	`CREATE_TIME` VARCHAR(14) NOT NULL COMMENT '등록일시' COLLATE 'utf8mb4_bin',
	`UPADTE_USER` VARCHAR(100) NOT NULL COMMENT '수정자' COLLATE 'utf8mb4_bin',
	`UPDATE_TIME` VARCHAR(14) NOT NULL COMMENT '수정일시' COLLATE 'utf8mb4_bin',
	PRIMARY KEY (`SRST_NO`)
)
COMMENT='결제정보'
COLLATE='utf8mb4_bin'
ENGINE=InnoDB
;


